/*
 * generated by Xtext
 */
package ch.fhnw.mdt.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import ch.fhnw.mdt.services.UForthGrammarAccess;

public class UForthParser extends AbstractContentAssistParser {
	
	@Inject
	private UForthGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected ch.fhnw.mdt.ui.contentassist.antlr.internal.InternalUForthParser createParser() {
		ch.fhnw.mdt.ui.contentassist.antlr.internal.InternalUForthParser result = new ch.fhnw.mdt.ui.contentassist.antlr.internal.InternalUForthParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getGlobalInstructionAccess().getAlternatives(), "rule__GlobalInstruction__Alternatives");
					put(grammarAccess.getKeywordsAccess().getNameAlternatives_0(), "rule__Keywords__NameAlternatives_0");
					put(grammarAccess.getInstructionAccess().getAlternatives(), "rule__Instruction__Alternatives");
					put(grammarAccess.getLiteralAccess().getAlternatives(), "rule__Literal__Alternatives");
					put(grammarAccess.getWordAccess().getNameAlternatives_0(), "rule__Word__NameAlternatives_0");
					put(grammarAccess.getFunctionAccess().getGroup(), "rule__Function__Group__0");
					put(grammarAccess.getForthAccess().getInstructionsAssignment(), "rule__Forth__InstructionsAssignment");
					put(grammarAccess.getFunctionAccess().getNameAssignment_1(), "rule__Function__NameAssignment_1");
					put(grammarAccess.getFunctionAccess().getWordsAssignment_2(), "rule__Function__WordsAssignment_2");
					put(grammarAccess.getKeywordsAccess().getNameAssignment(), "rule__Keywords__NameAssignment");
					put(grammarAccess.getInstructionAccess().getLitAssignment_2(), "rule__Instruction__LitAssignment_2");
					put(grammarAccess.getWordAccess().getNameAssignment(), "rule__Word__NameAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			ch.fhnw.mdt.ui.contentassist.antlr.internal.InternalUForthParser typedParser = (ch.fhnw.mdt.ui.contentassist.antlr.internal.InternalUForthParser) parser;
			typedParser.entryRuleForth();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public UForthGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(UForthGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
