/*
 * generated by Xtext
 */
package ch.fhnw.mdt.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.IXtextEditorCallback;

/**
 * Use this class to register components to be used within the IDE.
 */
public class UForthUiModule extends ch.fhnw.mdt.ui.AbstractUForthUiModule {
	public UForthUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends IXtextEditorCallback> bindIXtextEditorCallback() {
	    return null;
	}
}
