/*
 * generated by Xtext
 */
package ch.fhnw.mdt.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class UForthGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ForthElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Forth");
		private final Assignment cInstructionsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cInstructionsGlobalInstructionParserRuleCall_0 = (RuleCall)cInstructionsAssignment.eContents().get(0);
		
		//Forth:
		//	instructions+=GlobalInstruction*;
		@Override public ParserRule getRule() { return rule; }

		//instructions+=GlobalInstruction*
		public Assignment getInstructionsAssignment() { return cInstructionsAssignment; }

		//GlobalInstruction
		public RuleCall getInstructionsGlobalInstructionParserRuleCall_0() { return cInstructionsGlobalInstructionParserRuleCall_0; }
	}

	public class GlobalInstructionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "GlobalInstruction");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cCreateParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cFunctionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cWordParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//GlobalInstruction:
		//	Create | Function | Word;
		@Override public ParserRule getRule() { return rule; }

		//Create | Function | Word
		public Alternatives getAlternatives() { return cAlternatives; }

		//Create
		public RuleCall getCreateParserRuleCall_0() { return cCreateParserRuleCall_0; }

		//Function
		public RuleCall getFunctionParserRuleCall_1() { return cFunctionParserRuleCall_1; }

		//Word
		public RuleCall getWordParserRuleCall_2() { return cWordParserRuleCall_2; }
	}

	public class FunctionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Function");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cColonKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cWordsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cWordsWordParserRuleCall_2_0 = (RuleCall)cWordsAssignment_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Function:
		//	":" name=ID words+=Word* ";";
		@Override public ParserRule getRule() { return rule; }

		//":" name=ID words+=Word* ";"
		public Group getGroup() { return cGroup; }

		//":"
		public Keyword getColonKeyword_0() { return cColonKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//words+=Word*
		public Assignment getWordsAssignment_2() { return cWordsAssignment_2; }

		//Word
		public RuleCall getWordsWordParserRuleCall_2_0() { return cWordsWordParserRuleCall_2_0; }

		//";"
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}

	public class CreateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Create");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCreateKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Assignment cLitAssignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final RuleCall cLitLITERALParserRuleCall_2_0_0 = (RuleCall)cLitAssignment_2_0.eContents().get(0);
		private final Keyword cCommaKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		
		//Create:
		//	"create" name=ID (lit+=LITERAL ",")*;
		@Override public ParserRule getRule() { return rule; }

		//"create" name=ID (lit+=LITERAL ",")*
		public Group getGroup() { return cGroup; }

		//"create"
		public Keyword getCreateKeyword_0() { return cCreateKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//(lit+=LITERAL ",")*
		public Group getGroup_2() { return cGroup_2; }

		//lit+=LITERAL
		public Assignment getLitAssignment_2_0() { return cLitAssignment_2_0; }

		//LITERAL
		public RuleCall getLitLITERALParserRuleCall_2_0_0() { return cLitLITERALParserRuleCall_2_0_0; }

		//","
		public Keyword getCommaKeyword_2_1() { return cCommaKeyword_2_1; }
	}

	public class LITERALElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "LITERAL");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cDOUBLETerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//LITERAL:
		//	INT | DOUBLE;
		@Override public ParserRule getRule() { return rule; }

		//INT | DOUBLE
		public Alternatives getAlternatives() { return cAlternatives; }

		//INT
		public RuleCall getINTTerminalRuleCall_0() { return cINTTerminalRuleCall_0; }

		//DOUBLE
		public RuleCall getDOUBLETerminalRuleCall_1() { return cDOUBLETerminalRuleCall_1; }
	}

	public class IntrinsicStackWordsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "IntrinsicStackWords");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cIntrinsicStackWordsAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cNameAlternatives_1_0 = (Alternatives)cNameAssignment_1.eContents().get(0);
		private final Keyword cNameCLEARKeyword_1_0_0 = (Keyword)cNameAlternatives_1_0.eContents().get(0);
		private final Keyword cNameDROPKeyword_1_0_1 = (Keyword)cNameAlternatives_1_0.eContents().get(1);
		private final Keyword cNameDUPKeyword_1_0_2 = (Keyword)cNameAlternatives_1_0.eContents().get(2);
		private final Keyword cNameDUPKeyword_1_0_3 = (Keyword)cNameAlternatives_1_0.eContents().get(3);
		private final Keyword cNameSWAPKeyword_1_0_4 = (Keyword)cNameAlternatives_1_0.eContents().get(4);
		private final Keyword cNameNIPKeyword_1_0_5 = (Keyword)cNameAlternatives_1_0.eContents().get(5);
		private final Keyword cNameOVERKeyword_1_0_6 = (Keyword)cNameAlternatives_1_0.eContents().get(6);
		private final Keyword cNameROTKeyword_1_0_7 = (Keyword)cNameAlternatives_1_0.eContents().get(7);
		private final Keyword cNameROTKeyword_1_0_8 = (Keyword)cNameAlternatives_1_0.eContents().get(8);
		private final Keyword cNameTUCKKeyword_1_0_9 = (Keyword)cNameAlternatives_1_0.eContents().get(9);
		private final Keyword cNameUNDERKeyword_1_0_10 = (Keyword)cNameAlternatives_1_0.eContents().get(10);
		private final Keyword cName2DROPKeyword_1_0_11 = (Keyword)cNameAlternatives_1_0.eContents().get(11);
		private final Keyword cName2DUPKeyword_1_0_12 = (Keyword)cNameAlternatives_1_0.eContents().get(12);
		private final Keyword cName2SWAPKeyword_1_0_13 = (Keyword)cNameAlternatives_1_0.eContents().get(13);
		private final Keyword cName2OVERKeyword_1_0_14 = (Keyword)cNameAlternatives_1_0.eContents().get(14);
		private final Keyword cNameRCLEARKeyword_1_0_15 = (Keyword)cNameAlternatives_1_0.eContents().get(15);
		private final Keyword cNameRKeyword_1_0_16 = (Keyword)cNameAlternatives_1_0.eContents().get(16);
		private final Keyword cNameRKeyword_1_0_17 = (Keyword)cNameAlternatives_1_0.eContents().get(17);
		private final Keyword cNameRKeyword_1_0_18 = (Keyword)cNameAlternatives_1_0.eContents().get(18);
		private final Keyword cNameRDROPKeyword_1_0_19 = (Keyword)cNameAlternatives_1_0.eContents().get(19);
		
		//IntrinsicStackWords:
		//	{IntrinsicStackWords} name=("CLEAR" | "DROP" | "DUP" | "?DUP" | "SWAP" | "NIP" | "OVER" | "ROT" | "-ROT" | "TUCK" |
		//	"UNDER" | "2DROP" | "2DUP" | "2SWAP" | "2OVER" | "RCLEAR" | "R@" | "r>" | ">r" | "RDROP");
		@Override public ParserRule getRule() { return rule; }

		//{IntrinsicStackWords} name=("CLEAR" | "DROP" | "DUP" | "?DUP" | "SWAP" | "NIP" | "OVER" | "ROT" | "-ROT" | "TUCK" |
		//"UNDER" | "2DROP" | "2DUP" | "2SWAP" | "2OVER" | "RCLEAR" | "R@" | "r>" | ">r" | "RDROP")
		public Group getGroup() { return cGroup; }

		//{IntrinsicStackWords}
		public Action getIntrinsicStackWordsAction_0() { return cIntrinsicStackWordsAction_0; }

		//name=("CLEAR" | "DROP" | "DUP" | "?DUP" | "SWAP" | "NIP" | "OVER" | "ROT" | "-ROT" | "TUCK" | "UNDER" | "2DROP" | "2DUP"
		//| "2SWAP" | "2OVER" | "RCLEAR" | "R@" | "r>" | ">r" | "RDROP")
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//"CLEAR" | "DROP" | "DUP" | "?DUP" | "SWAP" | "NIP" | "OVER" | "ROT" | "-ROT" | "TUCK" | "UNDER" | "2DROP" | "2DUP" |
		//"2SWAP" | "2OVER" | "RCLEAR" | "R@" | "r>" | ">r" | "RDROP"
		public Alternatives getNameAlternatives_1_0() { return cNameAlternatives_1_0; }

		//"CLEAR"
		public Keyword getNameCLEARKeyword_1_0_0() { return cNameCLEARKeyword_1_0_0; }

		//"DROP"
		public Keyword getNameDROPKeyword_1_0_1() { return cNameDROPKeyword_1_0_1; }

		//"DUP"
		public Keyword getNameDUPKeyword_1_0_2() { return cNameDUPKeyword_1_0_2; }

		//"?DUP"
		public Keyword getNameDUPKeyword_1_0_3() { return cNameDUPKeyword_1_0_3; }

		//"SWAP"
		public Keyword getNameSWAPKeyword_1_0_4() { return cNameSWAPKeyword_1_0_4; }

		//"NIP"
		public Keyword getNameNIPKeyword_1_0_5() { return cNameNIPKeyword_1_0_5; }

		//"OVER"
		public Keyword getNameOVERKeyword_1_0_6() { return cNameOVERKeyword_1_0_6; }

		//"ROT"
		public Keyword getNameROTKeyword_1_0_7() { return cNameROTKeyword_1_0_7; }

		//"-ROT"
		public Keyword getNameROTKeyword_1_0_8() { return cNameROTKeyword_1_0_8; }

		//"TUCK"
		public Keyword getNameTUCKKeyword_1_0_9() { return cNameTUCKKeyword_1_0_9; }

		//"UNDER"
		public Keyword getNameUNDERKeyword_1_0_10() { return cNameUNDERKeyword_1_0_10; }

		//"2DROP"
		public Keyword getName2DROPKeyword_1_0_11() { return cName2DROPKeyword_1_0_11; }

		//"2DUP"
		public Keyword getName2DUPKeyword_1_0_12() { return cName2DUPKeyword_1_0_12; }

		//"2SWAP"
		public Keyword getName2SWAPKeyword_1_0_13() { return cName2SWAPKeyword_1_0_13; }

		//"2OVER"
		public Keyword getName2OVERKeyword_1_0_14() { return cName2OVERKeyword_1_0_14; }

		//"RCLEAR"
		public Keyword getNameRCLEARKeyword_1_0_15() { return cNameRCLEARKeyword_1_0_15; }

		//"R@"
		public Keyword getNameRKeyword_1_0_16() { return cNameRKeyword_1_0_16; }

		//"r>"
		public Keyword getNameRKeyword_1_0_17() { return cNameRKeyword_1_0_17; }

		//">r"
		public Keyword getNameRKeyword_1_0_18() { return cNameRKeyword_1_0_18; }

		//"RDROP"
		public Keyword getNameRDROPKeyword_1_0_19() { return cNameRDROPKeyword_1_0_19; }
	}

	public class IntrinsicMemoryWordsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "IntrinsicMemoryWords");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cIntrinsicMemoryWordsAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cNameAlternatives_1_0 = (Alternatives)cNameAssignment_1.eContents().get(0);
		private final Keyword cNameLDKeyword_1_0_0 = (Keyword)cNameAlternatives_1_0.eContents().get(0);
		private final Keyword cNameCommercialAtKeyword_1_0_1 = (Keyword)cNameAlternatives_1_0.eContents().get(1);
		private final Keyword cNameSTKeyword_1_0_2 = (Keyword)cNameAlternatives_1_0.eContents().get(2);
		private final Keyword cNameExclamationMarkKeyword_1_0_3 = (Keyword)cNameAlternatives_1_0.eContents().get(3);
		private final Keyword cName2Keyword_1_0_4 = (Keyword)cNameAlternatives_1_0.eContents().get(4);
		private final Keyword cName2Keyword_1_0_5 = (Keyword)cNameAlternatives_1_0.eContents().get(5);
		private final Keyword cNameLLDKeyword_1_0_6 = (Keyword)cNameAlternatives_1_0.eContents().get(6);
		private final Keyword cNameLKeyword_1_0_7 = (Keyword)cNameAlternatives_1_0.eContents().get(7);
		private final Keyword cNameLSTKeyword_1_0_8 = (Keyword)cNameAlternatives_1_0.eContents().get(8);
		private final Keyword cNameLKeyword_1_0_9 = (Keyword)cNameAlternatives_1_0.eContents().get(9);
		private final Keyword cNameTLDKeyword_1_0_10 = (Keyword)cNameAlternatives_1_0.eContents().get(10);
		private final Keyword cNameTKeyword_1_0_11 = (Keyword)cNameAlternatives_1_0.eContents().get(11);
		private final Keyword cNameTSTKeyword_1_0_12 = (Keyword)cNameAlternatives_1_0.eContents().get(12);
		private final Keyword cNameTKeyword_1_0_13 = (Keyword)cNameAlternatives_1_0.eContents().get(13);
		private final Keyword cNameSTKeyword_1_0_14 = (Keyword)cNameAlternatives_1_0.eContents().get(14);
		private final Keyword cNamePlusSignExclamationMarkKeyword_1_0_15 = (Keyword)cNameAlternatives_1_0.eContents().get(15);
		private final Keyword cNameINCKeyword_1_0_16 = (Keyword)cNameAlternatives_1_0.eContents().get(16);
		private final Keyword cNameDECKeyword_1_0_17 = (Keyword)cNameAlternatives_1_0.eContents().get(17);
		private final Keyword cNameONKeyword_1_0_18 = (Keyword)cNameAlternatives_1_0.eContents().get(18);
		private final Keyword cNameOFFKeyword_1_0_19 = (Keyword)cNameAlternatives_1_0.eContents().get(19);
		private final Keyword cNameERASEKeyword_1_0_20 = (Keyword)cNameAlternatives_1_0.eContents().get(20);
		private final Keyword cNameFILLKeyword_1_0_21 = (Keyword)cNameAlternatives_1_0.eContents().get(21);
		private final Keyword cNameCOUNTKeyword_1_0_22 = (Keyword)cNameAlternatives_1_0.eContents().get(22);
		private final Keyword cNameMOVEKeyword_1_0_23 = (Keyword)cNameAlternatives_1_0.eContents().get(23);
		private final Keyword cNamePLACEKeyword_1_0_24 = (Keyword)cNameAlternatives_1_0.eContents().get(24);
		
		//IntrinsicMemoryWords:
		//	{IntrinsicMemoryWords} name=("LD" | "@" | "ST" | "!" | "2@" | "2!" | "LLD" | "L@" | "LST" | "L!" | "TLD" | "T@" |
		//	"TST" | "T!" | "+ST" | "+!" | "INC" | "DEC" | "ON" | "OFF" | "ERASE" | "FILL" | "COUNT" | "MOVE" | "PLACE");
		@Override public ParserRule getRule() { return rule; }

		//{IntrinsicMemoryWords} name=("LD" | "@" | "ST" | "!" | "2@" | "2!" | "LLD" | "L@" | "LST" | "L!" | "TLD" | "T@" | "TST"
		//| "T!" | "+ST" | "+!" | "INC" | "DEC" | "ON" | "OFF" | "ERASE" | "FILL" | "COUNT" | "MOVE" | "PLACE")
		public Group getGroup() { return cGroup; }

		//{IntrinsicMemoryWords}
		public Action getIntrinsicMemoryWordsAction_0() { return cIntrinsicMemoryWordsAction_0; }

		//name=("LD" | "@" | "ST" | "!" | "2@" | "2!" | "LLD" | "L@" | "LST" | "L!" | "TLD" | "T@" | "TST" | "T!" | "+ST" | "+!" |
		//"INC" | "DEC" | "ON" | "OFF" | "ERASE" | "FILL" | "COUNT" | "MOVE" | "PLACE")
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//"LD" | "@" | "ST" | "!" | "2@" | "2!" | "LLD" | "L@" | "LST" | "L!" | "TLD" | "T@" | "TST" | "T!" | "+ST" | "+!" | "INC"
		//| "DEC" | "ON" | "OFF" | "ERASE" | "FILL" | "COUNT" | "MOVE" | "PLACE"
		public Alternatives getNameAlternatives_1_0() { return cNameAlternatives_1_0; }

		//"LD"
		public Keyword getNameLDKeyword_1_0_0() { return cNameLDKeyword_1_0_0; }

		//"@"
		public Keyword getNameCommercialAtKeyword_1_0_1() { return cNameCommercialAtKeyword_1_0_1; }

		//"ST"
		public Keyword getNameSTKeyword_1_0_2() { return cNameSTKeyword_1_0_2; }

		//"!"
		public Keyword getNameExclamationMarkKeyword_1_0_3() { return cNameExclamationMarkKeyword_1_0_3; }

		//"2@"
		public Keyword getName2Keyword_1_0_4() { return cName2Keyword_1_0_4; }

		//"2!"
		public Keyword getName2Keyword_1_0_5() { return cName2Keyword_1_0_5; }

		//"LLD"
		public Keyword getNameLLDKeyword_1_0_6() { return cNameLLDKeyword_1_0_6; }

		//"L@"
		public Keyword getNameLKeyword_1_0_7() { return cNameLKeyword_1_0_7; }

		//"LST"
		public Keyword getNameLSTKeyword_1_0_8() { return cNameLSTKeyword_1_0_8; }

		//"L!"
		public Keyword getNameLKeyword_1_0_9() { return cNameLKeyword_1_0_9; }

		//"TLD"
		public Keyword getNameTLDKeyword_1_0_10() { return cNameTLDKeyword_1_0_10; }

		//"T@"
		public Keyword getNameTKeyword_1_0_11() { return cNameTKeyword_1_0_11; }

		//"TST"
		public Keyword getNameTSTKeyword_1_0_12() { return cNameTSTKeyword_1_0_12; }

		//"T!"
		public Keyword getNameTKeyword_1_0_13() { return cNameTKeyword_1_0_13; }

		//"+ST"
		public Keyword getNameSTKeyword_1_0_14() { return cNameSTKeyword_1_0_14; }

		//"+!"
		public Keyword getNamePlusSignExclamationMarkKeyword_1_0_15() { return cNamePlusSignExclamationMarkKeyword_1_0_15; }

		//"INC"
		public Keyword getNameINCKeyword_1_0_16() { return cNameINCKeyword_1_0_16; }

		//"DEC"
		public Keyword getNameDECKeyword_1_0_17() { return cNameDECKeyword_1_0_17; }

		//"ON"
		public Keyword getNameONKeyword_1_0_18() { return cNameONKeyword_1_0_18; }

		//"OFF"
		public Keyword getNameOFFKeyword_1_0_19() { return cNameOFFKeyword_1_0_19; }

		//"ERASE"
		public Keyword getNameERASEKeyword_1_0_20() { return cNameERASEKeyword_1_0_20; }

		//"FILL"
		public Keyword getNameFILLKeyword_1_0_21() { return cNameFILLKeyword_1_0_21; }

		//"COUNT"
		public Keyword getNameCOUNTKeyword_1_0_22() { return cNameCOUNTKeyword_1_0_22; }

		//"MOVE"
		public Keyword getNameMOVEKeyword_1_0_23() { return cNameMOVEKeyword_1_0_23; }

		//"PLACE"
		public Keyword getNamePLACEKeyword_1_0_24() { return cNamePLACEKeyword_1_0_24; }
	}

	public class IntrinsicArithmeticWordsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "IntrinsicArithmeticWords");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cIntrinsicArithmeticWordsAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cNameAlternatives_1_0 = (Alternatives)cNameAssignment_1.eContents().get(0);
		private final Keyword cNamePlusSignKeyword_1_0_0 = (Keyword)cNameAlternatives_1_0.eContents().get(0);
		private final Keyword cNameHyphenMinusKeyword_1_0_1 = (Keyword)cNameAlternatives_1_0.eContents().get(1);
		private final Keyword cNameAsteriskKeyword_1_0_2 = (Keyword)cNameAlternatives_1_0.eContents().get(2);
		private final Keyword cNameSolidusKeyword_1_0_3 = (Keyword)cNameAlternatives_1_0.eContents().get(3);
		private final Keyword cName2Keyword_1_0_4 = (Keyword)cNameAlternatives_1_0.eContents().get(4);
		private final Keyword cName2Keyword_1_0_5 = (Keyword)cNameAlternatives_1_0.eContents().get(5);
		private final Keyword cNameU2Keyword_1_0_6 = (Keyword)cNameAlternatives_1_0.eContents().get(6);
		private final Keyword cNameRORKeyword_1_0_7 = (Keyword)cNameAlternatives_1_0.eContents().get(7);
		private final Keyword cNameDRORKeyword_1_0_8 = (Keyword)cNameAlternatives_1_0.eContents().get(8);
		private final Keyword cNameROLKeyword_1_0_9 = (Keyword)cNameAlternatives_1_0.eContents().get(9);
		private final Keyword cNameDROLKeyword_1_0_10 = (Keyword)cNameAlternatives_1_0.eContents().get(10);
		private final Keyword cNamePACKKeyword_1_0_11 = (Keyword)cNameAlternatives_1_0.eContents().get(11);
		private final Keyword cNameUNPACKKeyword_1_0_12 = (Keyword)cNameAlternatives_1_0.eContents().get(12);
		private final Keyword cNameSHIFTKeyword_1_0_13 = (Keyword)cNameAlternatives_1_0.eContents().get(13);
		private final Keyword cNameASHIFTKeyword_1_0_14 = (Keyword)cNameAlternatives_1_0.eContents().get(14);
		private final Keyword cName2Keyword_1_0_15 = (Keyword)cNameAlternatives_1_0.eContents().get(15);
		private final Keyword cName0Keyword_1_0_16 = (Keyword)cNameAlternatives_1_0.eContents().get(16);
		private final Keyword cName0Keyword_1_0_17 = (Keyword)cNameAlternatives_1_0.eContents().get(17);
		private final Keyword cName0Keyword_1_0_18 = (Keyword)cNameAlternatives_1_0.eContents().get(18);
		private final Keyword cNameD0Keyword_1_0_19 = (Keyword)cNameAlternatives_1_0.eContents().get(19);
		private final Keyword cNameNEGATEKeyword_1_0_20 = (Keyword)cNameAlternatives_1_0.eContents().get(20);
		private final Keyword cNameDNEGATEKeyword_1_0_21 = (Keyword)cNameAlternatives_1_0.eContents().get(21);
		private final Keyword cName1Keyword_1_0_22 = (Keyword)cNameAlternatives_1_0.eContents().get(22);
		private final Keyword cName1Keyword_1_0_23 = (Keyword)cNameAlternatives_1_0.eContents().get(23);
		private final Keyword cNameTRUEKeyword_1_0_24 = (Keyword)cNameAlternatives_1_0.eContents().get(24);
		private final Keyword cNameFALSEKeyword_1_0_25 = (Keyword)cNameAlternatives_1_0.eContents().get(25);
		private final Keyword cNameCELLKeyword_1_0_26 = (Keyword)cNameAlternatives_1_0.eContents().get(26);
		private final Keyword cNameCELLKeyword_1_0_27 = (Keyword)cNameAlternatives_1_0.eContents().get(27);
		private final Keyword cNameCARRY_RESETKeyword_1_0_28 = (Keyword)cNameAlternatives_1_0.eContents().get(28);
		private final Keyword cNameCARRYSETKeyword_1_0_29 = (Keyword)cNameAlternatives_1_0.eContents().get(29);
		private final Keyword cNameABSKeyword_1_0_30 = (Keyword)cNameAlternatives_1_0.eContents().get(30);
		private final Keyword cNameDABSKeyword_1_0_31 = (Keyword)cNameAlternatives_1_0.eContents().get(31);
		private final Keyword cNameEXTENDKeyword_1_0_32 = (Keyword)cNameAlternatives_1_0.eContents().get(32);
		
		//IntrinsicArithmeticWords:
		//	{IntrinsicArithmeticWords} name=("+" | "-" | "*" | "/" | "2*" | "2/" | "u2/" | "ROR" | "DROR" | "ROL" | "DROL" |
		//	"PACK" | "UNPACK" | "SHIFT" | "ASHIFT" | "2**" | "0=" | "0<>" | "0<" | "d0=" | "NEGATE" | "DNEGATE" | "1+" | "1-" |
		//	"TRUE" | "FALSE" | "CELL+" | "CELL-" | "CARRY_RESET" | "CARRY-SET" | "ABS" | "DABS" | "EXTEND");
		@Override public ParserRule getRule() { return rule; }

		//{IntrinsicArithmeticWords} name=("+" | "-" | "*" | "/" | "2*" | "2/" | "u2/" | "ROR" | "DROR" | "ROL" | "DROL" | "PACK"
		//| "UNPACK" | "SHIFT" | "ASHIFT" | "2**" | "0=" | "0<>" | "0<" | "d0=" | "NEGATE" | "DNEGATE" | "1+" | "1-" | "TRUE" |
		//"FALSE" | "CELL+" | "CELL-" | "CARRY_RESET" | "CARRY-SET" | "ABS" | "DABS" | "EXTEND")
		public Group getGroup() { return cGroup; }

		//{IntrinsicArithmeticWords}
		public Action getIntrinsicArithmeticWordsAction_0() { return cIntrinsicArithmeticWordsAction_0; }

		//name=("+" | "-" | "*" | "/" | "2*" | "2/" | "u2/" | "ROR" | "DROR" | "ROL" | "DROL" | "PACK" | "UNPACK" | "SHIFT" |
		//"ASHIFT" | "2**" | "0=" | "0<>" | "0<" | "d0=" | "NEGATE" | "DNEGATE" | "1+" | "1-" | "TRUE" | "FALSE" | "CELL+" |
		//"CELL-" | "CARRY_RESET" | "CARRY-SET" | "ABS" | "DABS" | "EXTEND")
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//"+" | "-" | "*" | "/" | "2*" | "2/" | "u2/" | "ROR" | "DROR" | "ROL" | "DROL" | "PACK" | "UNPACK" | "SHIFT" | "ASHIFT" |
		//"2**" | "0=" | "0<>" | "0<" | "d0=" | "NEGATE" | "DNEGATE" | "1+" | "1-" | "TRUE" | "FALSE" | "CELL+" | "CELL-" |
		//"CARRY_RESET" | "CARRY-SET" | "ABS" | "DABS" | "EXTEND"
		public Alternatives getNameAlternatives_1_0() { return cNameAlternatives_1_0; }

		//"+"
		public Keyword getNamePlusSignKeyword_1_0_0() { return cNamePlusSignKeyword_1_0_0; }

		//"-"
		public Keyword getNameHyphenMinusKeyword_1_0_1() { return cNameHyphenMinusKeyword_1_0_1; }

		//"*"
		public Keyword getNameAsteriskKeyword_1_0_2() { return cNameAsteriskKeyword_1_0_2; }

		//"/"
		public Keyword getNameSolidusKeyword_1_0_3() { return cNameSolidusKeyword_1_0_3; }

		//"2*"
		public Keyword getName2Keyword_1_0_4() { return cName2Keyword_1_0_4; }

		//"2/"
		public Keyword getName2Keyword_1_0_5() { return cName2Keyword_1_0_5; }

		//"u2/"
		public Keyword getNameU2Keyword_1_0_6() { return cNameU2Keyword_1_0_6; }

		//"ROR"
		public Keyword getNameRORKeyword_1_0_7() { return cNameRORKeyword_1_0_7; }

		//"DROR"
		public Keyword getNameDRORKeyword_1_0_8() { return cNameDRORKeyword_1_0_8; }

		//"ROL"
		public Keyword getNameROLKeyword_1_0_9() { return cNameROLKeyword_1_0_9; }

		//"DROL"
		public Keyword getNameDROLKeyword_1_0_10() { return cNameDROLKeyword_1_0_10; }

		//"PACK"
		public Keyword getNamePACKKeyword_1_0_11() { return cNamePACKKeyword_1_0_11; }

		//"UNPACK"
		public Keyword getNameUNPACKKeyword_1_0_12() { return cNameUNPACKKeyword_1_0_12; }

		//"SHIFT"
		public Keyword getNameSHIFTKeyword_1_0_13() { return cNameSHIFTKeyword_1_0_13; }

		//"ASHIFT"
		public Keyword getNameASHIFTKeyword_1_0_14() { return cNameASHIFTKeyword_1_0_14; }

		//"2**"
		public Keyword getName2Keyword_1_0_15() { return cName2Keyword_1_0_15; }

		//"0="
		public Keyword getName0Keyword_1_0_16() { return cName0Keyword_1_0_16; }

		//"0<>"
		public Keyword getName0Keyword_1_0_17() { return cName0Keyword_1_0_17; }

		//"0<"
		public Keyword getName0Keyword_1_0_18() { return cName0Keyword_1_0_18; }

		//"d0="
		public Keyword getNameD0Keyword_1_0_19() { return cNameD0Keyword_1_0_19; }

		//"NEGATE"
		public Keyword getNameNEGATEKeyword_1_0_20() { return cNameNEGATEKeyword_1_0_20; }

		//"DNEGATE"
		public Keyword getNameDNEGATEKeyword_1_0_21() { return cNameDNEGATEKeyword_1_0_21; }

		//"1+"
		public Keyword getName1Keyword_1_0_22() { return cName1Keyword_1_0_22; }

		//"1-"
		public Keyword getName1Keyword_1_0_23() { return cName1Keyword_1_0_23; }

		//"TRUE"
		public Keyword getNameTRUEKeyword_1_0_24() { return cNameTRUEKeyword_1_0_24; }

		//"FALSE"
		public Keyword getNameFALSEKeyword_1_0_25() { return cNameFALSEKeyword_1_0_25; }

		//"CELL+"
		public Keyword getNameCELLKeyword_1_0_26() { return cNameCELLKeyword_1_0_26; }

		//"CELL-"
		public Keyword getNameCELLKeyword_1_0_27() { return cNameCELLKeyword_1_0_27; }

		//"CARRY_RESET"
		public Keyword getNameCARRY_RESETKeyword_1_0_28() { return cNameCARRY_RESETKeyword_1_0_28; }

		//"CARRY-SET"
		public Keyword getNameCARRYSETKeyword_1_0_29() { return cNameCARRYSETKeyword_1_0_29; }

		//"ABS"
		public Keyword getNameABSKeyword_1_0_30() { return cNameABSKeyword_1_0_30; }

		//"DABS"
		public Keyword getNameDABSKeyword_1_0_31() { return cNameDABSKeyword_1_0_31; }

		//"EXTEND"
		public Keyword getNameEXTENDKeyword_1_0_32() { return cNameEXTENDKeyword_1_0_32; }
	}

	public class WordElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Word");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cIntrinsicStackWordsParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIntrinsicMemoryWordsParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cIntrinsicArithmeticWordsParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cAlternatives.eContents().get(3);
		private final RuleCall cNameLITERALParserRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Assignment cNameAssignment_4 = (Assignment)cAlternatives.eContents().get(4);
		private final RuleCall cNameIDTerminalRuleCall_4_0 = (RuleCall)cNameAssignment_4.eContents().get(0);
		
		//Word:
		//	IntrinsicStackWords | IntrinsicMemoryWords | IntrinsicArithmeticWords | name=LITERAL | name=ID;
		@Override public ParserRule getRule() { return rule; }

		//IntrinsicStackWords | IntrinsicMemoryWords | IntrinsicArithmeticWords | name=LITERAL | name=ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//IntrinsicStackWords
		public RuleCall getIntrinsicStackWordsParserRuleCall_0() { return cIntrinsicStackWordsParserRuleCall_0; }

		//IntrinsicMemoryWords
		public RuleCall getIntrinsicMemoryWordsParserRuleCall_1() { return cIntrinsicMemoryWordsParserRuleCall_1; }

		//IntrinsicArithmeticWords
		public RuleCall getIntrinsicArithmeticWordsParserRuleCall_2() { return cIntrinsicArithmeticWordsParserRuleCall_2; }

		//name=LITERAL
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }

		//LITERAL
		public RuleCall getNameLITERALParserRuleCall_3_0() { return cNameLITERALParserRuleCall_3_0; }

		//name=ID
		public Assignment getNameAssignment_4() { return cNameAssignment_4; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_4_0() { return cNameIDTerminalRuleCall_4_0; }
	}
	
	
	private final ForthElements pForth;
	private final TerminalRule tDIGIT;
	private final TerminalRule tDECINT;
	private final TerminalRule tSL_COMMENT;
	private final TerminalRule tINT;
	private final TerminalRule tDOUBLE;
	private final TerminalRule tID;
	private final GlobalInstructionElements pGlobalInstruction;
	private final FunctionElements pFunction;
	private final CreateElements pCreate;
	private final LITERALElements pLITERAL;
	private final IntrinsicStackWordsElements pIntrinsicStackWords;
	private final IntrinsicMemoryWordsElements pIntrinsicMemoryWords;
	private final IntrinsicArithmeticWordsElements pIntrinsicArithmeticWords;
	private final WordElements pWord;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public UForthGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pForth = new ForthElements();
		this.tDIGIT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "DIGIT");
		this.tDECINT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "DECINT");
		this.tSL_COMMENT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "SL_COMMENT");
		this.tINT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "INT");
		this.tDOUBLE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "DOUBLE");
		this.tID = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "ID");
		this.pGlobalInstruction = new GlobalInstructionElements();
		this.pFunction = new FunctionElements();
		this.pCreate = new CreateElements();
		this.pLITERAL = new LITERALElements();
		this.pIntrinsicStackWords = new IntrinsicStackWordsElements();
		this.pIntrinsicMemoryWords = new IntrinsicMemoryWordsElements();
		this.pIntrinsicArithmeticWords = new IntrinsicArithmeticWordsElements();
		this.pWord = new WordElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("ch.fhnw.mdt.UForth".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Forth:
	//	instructions+=GlobalInstruction*;
	public ForthElements getForthAccess() {
		return pForth;
	}
	
	public ParserRule getForthRule() {
		return getForthAccess().getRule();
	}

	//terminal fragment DIGIT:
	//	"0".."9";
	public TerminalRule getDIGITRule() {
		return tDIGIT;
	} 

	//terminal fragment DECINT:
	//	DIGIT+;
	public TerminalRule getDECINTRule() {
		return tDECINT;
	} 

	//terminal SL_COMMENT:
	//	"(" !("\n" | "\r")* ")" WS*;
	public TerminalRule getSL_COMMENTRule() {
		return tSL_COMMENT;
	} 

	//terminal INT returns ecore::EInt:
	//	"-"? ("0".."9" | "A".."F")+;
	public TerminalRule getINTRule() {
		return tINT;
	} 

	//terminal DOUBLE returns ecore::EDouble:
	//	DECINT ("." DIGIT* | ("." DIGIT*)? ("E" | "e") ("-" | "+")? DECINT);
	public TerminalRule getDOUBLERule() {
		return tDOUBLE;
	} 

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_" | "!" | "@" | "?" | "," | "<" | ">" | "=") ("a".."z" | "A".."Z" | "_" | "!" | "?" |
	//	"@" | "<" | ">" | "0".."9" | "," | "=")*;
	public TerminalRule getIDRule() {
		return tID;
	} 

	//GlobalInstruction:
	//	Create | Function | Word;
	public GlobalInstructionElements getGlobalInstructionAccess() {
		return pGlobalInstruction;
	}
	
	public ParserRule getGlobalInstructionRule() {
		return getGlobalInstructionAccess().getRule();
	}

	//Function:
	//	":" name=ID words+=Word* ";";
	public FunctionElements getFunctionAccess() {
		return pFunction;
	}
	
	public ParserRule getFunctionRule() {
		return getFunctionAccess().getRule();
	}

	//Create:
	//	"create" name=ID (lit+=LITERAL ",")*;
	public CreateElements getCreateAccess() {
		return pCreate;
	}
	
	public ParserRule getCreateRule() {
		return getCreateAccess().getRule();
	}

	//LITERAL:
	//	INT | DOUBLE;
	public LITERALElements getLITERALAccess() {
		return pLITERAL;
	}
	
	public ParserRule getLITERALRule() {
		return getLITERALAccess().getRule();
	}

	//IntrinsicStackWords:
	//	{IntrinsicStackWords} name=("CLEAR" | "DROP" | "DUP" | "?DUP" | "SWAP" | "NIP" | "OVER" | "ROT" | "-ROT" | "TUCK" |
	//	"UNDER" | "2DROP" | "2DUP" | "2SWAP" | "2OVER" | "RCLEAR" | "R@" | "r>" | ">r" | "RDROP");
	public IntrinsicStackWordsElements getIntrinsicStackWordsAccess() {
		return pIntrinsicStackWords;
	}
	
	public ParserRule getIntrinsicStackWordsRule() {
		return getIntrinsicStackWordsAccess().getRule();
	}

	//IntrinsicMemoryWords:
	//	{IntrinsicMemoryWords} name=("LD" | "@" | "ST" | "!" | "2@" | "2!" | "LLD" | "L@" | "LST" | "L!" | "TLD" | "T@" |
	//	"TST" | "T!" | "+ST" | "+!" | "INC" | "DEC" | "ON" | "OFF" | "ERASE" | "FILL" | "COUNT" | "MOVE" | "PLACE");
	public IntrinsicMemoryWordsElements getIntrinsicMemoryWordsAccess() {
		return pIntrinsicMemoryWords;
	}
	
	public ParserRule getIntrinsicMemoryWordsRule() {
		return getIntrinsicMemoryWordsAccess().getRule();
	}

	//IntrinsicArithmeticWords:
	//	{IntrinsicArithmeticWords} name=("+" | "-" | "*" | "/" | "2*" | "2/" | "u2/" | "ROR" | "DROR" | "ROL" | "DROL" |
	//	"PACK" | "UNPACK" | "SHIFT" | "ASHIFT" | "2**" | "0=" | "0<>" | "0<" | "d0=" | "NEGATE" | "DNEGATE" | "1+" | "1-" |
	//	"TRUE" | "FALSE" | "CELL+" | "CELL-" | "CARRY_RESET" | "CARRY-SET" | "ABS" | "DABS" | "EXTEND");
	public IntrinsicArithmeticWordsElements getIntrinsicArithmeticWordsAccess() {
		return pIntrinsicArithmeticWords;
	}
	
	public ParserRule getIntrinsicArithmeticWordsRule() {
		return getIntrinsicArithmeticWordsAccess().getRule();
	}

	//Word:
	//	IntrinsicStackWords | IntrinsicMemoryWords | IntrinsicArithmeticWords | name=LITERAL | name=ID;
	public WordElements getWordAccess() {
		return pWord;
	}
	
	public ParserRule getWordRule() {
		return getWordAccess().getRule();
	}

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
