/*
 * generated by Xtext
 */
package ch.fhnw.mdt.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractUForthValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(ch.fhnw.mdt.uForth.UForthPackage.eINSTANCE);
		return result;
	}
}
