/*
 * generated by Xtext
 */
package ch.fhnw.mdt.ui.contentassist

import ch.fhnw.mdt.ui.contentassist.AbstractUForthProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class UForthProposalProvider extends AbstractUForthProposalProvider {
}
