/*
 * generated by Xtext
 */
package ch.fhnw.mdt;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class UForthStandaloneSetup extends UForthStandaloneSetupGenerated{

	public static void doSetup() {
		new UForthStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

