/*
 * generated by Xtext
 */
package ch.fhnw.mdt;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class UForthRuntimeModule extends ch.fhnw.mdt.AbstractUForthRuntimeModule {

}
